/* Contenido transcrito del menú oficial de El Papalote Taco & Grill (PDF en assets/menu/papalote-menu.pdf) */
const MENU_DATA = [
  {
    id: "entradas",
    name: "Entradas",
    items: [
      { name: "Dip de Alcachofa", price: "$259", desc: "Delicioso dip de alcachofa y espinaca a base de queso crema, mozzarella y Parmesano. Acompañado de pan tostado." },
      { name: "Guacamole", price: "$145", desc: "Con cebolla, serrano y tomate picado." },
      { name: "Queso Flameado", price: "$149", desc: "Con chorizo 100% carne de puerco." },
      { name: "Queso Planchado", price: "$199", desc: "Queso fresco planchado con un toque de orégano, pico de gallo y servido sobre salsa de tomate." },
      { name: "Champiñones", price: "$159", desc: "Salteados preparados a la bilbaína, al ajillo o al cilantro." },
      { name: "Camarones", price: "$249", desc: "Salteados preparados al ajillo o al cilantro." },
      { name: "Mozzarella Sticks", price: "$119", desc: "8 palitos de queso mozzarella empanizados, con salsa marinara." },
      { name: "Empalmes", tag: "Nuevo", price: "1/2 orden $99 | Orden $175", desc: "En tortilla de maíz, de chicharrón en salsa verde con frijoles refritos. Acompañados de aderezo chipotle." },
      { name: "Muslos de Pollo", price: "$309", desc: "Con hueso y piel, sazonados y asados a la parrilla. Bañados con salsa bbq original, búfalo o bbq sweet n' spicy." },
      { name: "Jalapeño Poppers", price: "$115", desc: "4 chilitos jalapeño empanizados y rellenos de queso crema con habanero-bbq." },
      { name: "Jalapeño Wraps", price: "2 pzas $189 | 4 pzas $309", desc: "Rellenos de queso Philadelphia, envueltos en tocino y asados a la parrilla, sobre cama de arroz al cilantro." },
      { name: "Atropellado", price: "$275", desc: "Carne seca molida preparada con salsa de tomate, cebolla y serrano. Acompañado de frijoles con veneno." },
      { name: "Cáscaras de Papa", price: "4 pzas $149 | 8 pzs $265", desc: "Doraditas cubiertas de queso gratinado, tocino y jalapeño. Agrega arrachera para 4 pz $86 | para 8 pz $134." },
      { name: "Buffalo Wings", price: "$189", desc: "Bañadas con salsa picosita, acompañadas con aderezo blue cheese." },
    ],
  },
  {
    id: "ensaladas",
    name: "Ensaladas",
    items: [
      { name: "De la Casa", price: "$99 | Con Pollo $199", desc: "Mezcla de lechugas, tocino, tomate, zanahoria, huevo duro, queso Cheddar y crotones." },
      { name: "César", price: "$199 | Con Pollo $269 | Camarones $259", desc: "Lechuga romana con aderezo César de la casa, queso Parmesano y crotones." },
      { name: "Fried Fish Parmesan", price: "$189", desc: "Ensalada de la Casa con filetitos de pescado empanizado y queso Parmesano." },
      { name: "Crispy Chicken Salad", price: "$219", desc: "Ensalada de la Casa con filetitos de pollo empanizados, tocino y queso Americano." },
      { name: "Baja Steak Salad", price: "$285", desc: "Ensalada de la Casa con arrachera, champiñones salteados y queso Parmesano. Pídela con aderezo Ranch." },
    ],
  },
  {
    id: "sopas",
    name: "Sopas y Caldos",
    items: [
      { name: "Sopa de Tortilla", price: "Ch $99 | Gde $125", desc: "Gratinada con queso Monterrey Jack." },
      { name: "Frijoles a la Charra", price: "Ch $49 | Gde $69", desc: "Frijoles enteros con tocino, chorizo, cilantro y chile jalapeño en rodajas." },
      { name: "Caldo Tlalpeño", price: "$179", desc: "Consomé de pollo con pollo, arroz y verduras." },
      { name: "Crema Conde", price: "Ch $75 | Gde $119", desc: "Crema de frijol con tostadas de maíz y crema." },
      { name: "Sopa de Fideo con Carne", price: "Ch $105 | Gde $119", desc: "Tradicional sopa de fideo con trozos de carne de res." },
    ],
  },
  {
    id: "clasicos",
    name: "Los Clásicos",
    note: "Pídelos de 2 ó 3 tacos, en tortilla de maíz o harina. Acompañados de frijoles refritos y papas sazonadas.",
    items: [
      { name: "Santa Fe", desc: "Queso Chihuahua, tocino, cebolla, chile jalapeño y guacamole.", price: "Pollo $195/$255 | Camarón $225/$299 | Arrachera $289/$389" },
      { name: "Machos", desc: "Cebolla, tocino, chile jalapeño y piquín.", price: "Pollo $169/$205 | Top-Sirloin $199/$265 | Camarón $185/$239" },
      { name: "Papalote", desc: "Cebolla, tocino, pimiento morrón y champiñones.", price: "Arrachera $265/$359 | Camarón $195/$259" },
      { name: "Monterrey", desc: "Queso Chihuahua y guacamole.", price: "Pollo $185/$239 | Camarón $205/$269 | Arrachera $279/$389" },
      { name: "El Paso", desc: "Arrachera adobada.", price: "$245 / $329" },
      { name: "Santa Rosa", desc: "Con queso Chihuahua.", price: "Arrachera adobada $279/$379 | Camarón $199/$265" },
      { name: "Álamo", desc: "Con queso Chihuahua, cebolla, pimiento morrón y champiñones.", price: "Pollo $169/$209 | Camarón $205/$265" },
      { name: "Coyote", desc: "Prime-rib picadito, tocino, queso, cebolla y cilantro arriba.", price: "$235 / $319" },
      { name: "Baja", desc: "Con queso Chihuahua y champiñones.", price: "Arrachera $265/$365 | Camarón $199/$269" },
      { name: "Mesquite", desc: "Con queso Chihuahua y tocino.", price: "Arrachera $285/$385 | Camarón $209/$279" },
      { name: "Establo", desc: "Prime-Rib, picadito, cebolla y cilantro arriba.", price: "$199 / $269" },
      { name: "Norteño", price: "Top-Sirloin $195/$259 | Arrachera $245/$329 | Camarón con queso $189/$249" },
      { name: "Corral", desc: "250 g de Sirloin a la parrilla y cortado en cuadritos. Las tortillas se sirven aparte.", price: "$319" },
      { name: "Colorado", desc: "Pollo, queso americano, lechuga y tomate.", price: "$165 / $209" },
      { name: "Cabo", desc: "Pescado empanizado, queso, lechuga, tomate y chipotle-mayo.", price: "$195 / $245" },
      { name: "Península", desc: "Pescado, queso, champiñones, pimiento morrón, cebolla y chipotle-mayo.", price: "$199 / $269" },
    ],
  },
  {
    id: "fajitas",
    name: "Fajitas",
    note: "Acompañadas de frijoles refritos y papas sazonadas.",
    items: [
      { name: "Rodeo Fajita", desc: "250 g de fajitas servidas sobre rajas de cebolla y pimiento morrón.", price: "Pollo $209 | Arrachera $389 | Mixta $299" },
      { name: "Rodeo Fajita para 2", desc: "Igual que el Rodeo Fajita pero con doble porción.", price: "Pollo $325 | Arrachera $689 | Mixta $509" },
      { name: "Parrillada Papalote (4 personas)", desc: "Fajitas acompañadas de Steak Fries, frijoles refritos, rajas de cebolla y pimiento morrón.", price: "Sirloin 1kg $1,109 | Arrachera 1kg $1,239 | Mixta 1kg $1,119" },
      { name: "Papalote Loaded Fajitas", price: "$419", desc: "Combinación de 220 g de fajitas de res, tocino, champiñones, rajas de cebolla y pimiento morrón bien acitronadas." },
    ],
  },
  {
    id: "street-tacos",
    name: "Street Tacos",
    tag: "Nuevos",
    note: "Pídelos de 2 ó 3 tacos, en tortilla taquera de maíz o harina. Acompáñalos con 1 guarnición.",
    items: [
      { name: "De Arrachera Adobada", price: "$259 / $339", desc: "Con costra de queso, cebolla salteada y cilantro fresco." },
      { name: "De Camarones al Cilantro y Chipotle", price: "$185 / $229", desc: "Chile ancho, chipotle-mayo y queso Cotija." },
      { name: "De Rib Eye", price: "$209 / $275", desc: "Con frijoles refritos embarrados, cebolla salteada, chile serrano y cilantro fresco." },
      { name: "De Fideo Seco", price: "$169 / $219", desc: "Con frijoles refritos embarrados, chipotle-mayo, tocino, cilantro y queso Cotija." },
      { name: "De Chipotle Boneless", price: "$169 / $209", desc: "Con costra de queso, lechuga, tomate y chipotle-mayo." },
    ],
  },
  {
    id: "grill",
    name: "Del Grill",
    note: "Acompañados con ensalada de la casa y 1 guarnición a elegir.",
    items: [
      { name: "Rib-Eye", price: "12 oz (340 g) $609 | 16 oz (454 g) $729", desc: "Prueba nuestro steak más jugoso Certified Angus Beef®." },
      { name: "Cowboy Rib-Eye", price: "18 oz (510 g) $789", desc: "A nuestro jugoso Rib-Eye le dejamos el hueso, para darle aún más sabor. Certified Angus Beef®." },
      { name: "Arrachera Outside", price: "10 oz (283 g) $589", desc: "Un steak delgado, jugoso, suave y con gran sabor. Certified Angus Beef®." },
      { name: "Top-Sirloin", price: "10 oz (283 g) $349", desc: "Un steak con poca grasa y gran sabor." },
      { name: "Alambre", price: "Pollo $279 | Sirloin $375 | Arrachera $419", desc: "250 g con cebolla, morrón y tocino." },
      { name: "Papalote Grilled Chicken", price: "250 g $229", desc: "Pechuga de pollo sazonada y asada a la parrilla." },
    ],
    footnote: "*Los gramajes de nuestra carne son en crudo y aproximados. Guarniciones: aros de cebolla, papas a la francesa, papa al horno, steak fries, papas sazonadas, arroz, frijoles refritos.",
  },
  {
    id: "burgers",
    name: "Burgers",
    items: [
      { name: "Old Fashioned Cheeseburger", price: "1/3 lb $219 | 1/2 lb $249", desc: "100% de res, Certified Angus Beef® con queso Americano o Monterrey Jack, lechuga, tomate y pickles." },
      { name: "Chipotle Burger", price: "1/3 lb $249 | 1/2 lb $289", desc: "Con queso cheddar, tocino, lechuga, tomate y chipotle-mayo." },
      { name: "Backyard Burger", price: "1/3 lb $259 | 1/2 lb $295", desc: "Con queso cheddar, tocino, aros de cebolla y smoked-bbq." },
      { name: "Jalapeño Popper Burger", price: "1/3 lb $259 | 1/2 lb $285", desc: "Con 2 jalapeños rellenos de queso crema, tocino y habanero-bbq." },
      { name: "Monster Burger", price: "1/3 lb $305", desc: "Doble carne de 1/3 lb, queso cheddar, cebolla caramelizada, tocino y mostaza Dijon. Pídela Super Monster con doble carne de 1/2 lb $379." },
      { name: "Chipotle Chicken Burger", desc: "Pechuga de pollo empanizada con chipotle-mayo, queso, lechuga, tomate y pickles." },
      { name: "Chicken Burger", price: "$199", desc: "Pechuga de pollo con queso Americano o Monterrey Jack, tocino, lechuga, tomate y pickles." },
    ],
    footnote: "Extras: guacamole, salsa BBQ, aros de cebolla, cebollas salteadas, champiñones salteados y tocino +$42 c/u.",
  },
  {
    id: "especialidades",
    name: "Especialidades",
    items: [
      { name: "Country Chicken", price: "$355", desc: "Filetitos de pollo empanizados acompañados con elote, papa al horno y ensalada." },
      { name: "Papa Asada Norteña", price: "$305", desc: "Con prime-rib, mantequilla, queso Chihuahua, crema ácida y tocino." },
      { name: "Fish n' Chips", price: "$289", desc: "Filete de pescado empanizado con papas steak fries, elote, salsa tártara y ensalada." },
      { name: "Cortadillo Borracho", price: "$369", desc: "De sirloin y prime-rib con salsa de cerveza obscura y tomate, pimientos, cebolla y serrano. Acompañado de arroz y frijoles refritos." },
    ],
  },
  {
    id: "sandwiches",
    name: "Sandwiches",
    items: [
      { name: "Nuevo México Steak Sandwich", price: "$379", desc: "De fajita de arrachera con queso Chihuahua, guacamole y tocino." },
      { name: "Sheriff Steak Sandwich", price: "$379", desc: "De fajita de arrachera con queso Chihuahua, tocino, aros de cebolla y chipotle-mayo." },
      { name: "Western Chicken Sandwich", price: "$279", desc: "De pechuga de pollo con queso Monterrey Jack, tocino, lechuga, tomate y chipotle-mayo." },
      { name: "Fried Fish Sandwich", price: "$299", desc: "De filete de pescado empanizado con queso Monterrey Jack, lechuga, tomate y salsa tártara." },
    ],
  },
  {
    id: "kids",
    name: "Kids",
    note: "Acompañados con papas a la francesa. Agrega limonada o naranjada Kids $29.",
    items: [
      { name: "Chicken Fingers", price: "$149", desc: "Filetitos de pollo empanizados." },
      { name: "Beef Quesadillas", price: "$169", desc: "2 quesadillas en tortilla de harina con arrachera picadita." },
      { name: "Burritos", price: "$159", desc: "2 burritos de frijoles con carne." },
      { name: "Chicken Bites", price: "$149", desc: "Bolitas de pechuga de pollo empanizadas." },
      { name: "Junior Burger", price: "$175", desc: "Hamburguesa chica con queso Americano." },
      { name: "Crispy Chicken Burger", price: "$169", desc: "De pechuga de pollo empanizada y queso Americano." },
    ],
  },
  {
    id: "postres",
    name: "Postres",
    items: [
      { name: "Tortuga Cheesecake", price: "$189", desc: "Cheesecake de vainilla cubierto con topping de caramelo, fudge y nuez." },
      { name: "Ultimate Lemon Cheesecake", price: "$185", desc: "Cheesecake de limón con cubierta cremosa y base de galleta de chocolate." },
      { name: "Sweet Shots", price: "$159", desc: "Postre frío individual en vaso de 6 oz. Disponible en 5 sabores: limón, flan, chocolate, moka y mango." },
      { name: "Supremo de Elote", price: "$179", desc: "Pan de elote receta original de la casa, servido caliente con topping cremoso, cajeta y canela." },
    ],
  },
];
